name: Upload Playwright Tests to Currents
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  basicTests:
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3]   # 3 parallel shards
        shardTotal: [3]

    name: "Playwright Tests - pwc"
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    container: mcr.microsoft.com/playwright:v1.49.0-jammy

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - run: |
          echo "$GITHUB_WORKSPACE"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Create .env file
        run: |
          echo "USERNAME=${{ secrets.USERNAME }}" >> .env
          echo "USERNAME1=${{ secrets.USERNAME1 }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "NEW_PASSWORD=${{ secrets.NEW_PASSWORD }}" >> .env
          echo "FIRST_NAME=${{ secrets.FIRST_NAME }}" >> .env
          echo "STREET_NAME=${{ secrets.STREET_NAME }}" >> .env
          echo "CITY=${{ secrets.CITY }}" >> .env
          echo "STATE=${{ secrets.STATE }}" >> .env
          echo "COUNTRY=${{ secrets.COUNTRY }}" >> .env
          echo "ZIP_CODE=${{ secrets.ZIP_CODE }}" >> .env
          echo "SFIRST_NAME=${{ secrets.SFIRST_NAME }}" >> .env
          echo "SEMAIL=${{ secrets.SEMAIL }}" >> .env
          echo "SCITY=${{ secrets.SCITY }}" >> .env
          echo "SSTATE=${{ secrets.SSTATE }}" >> .env
          echo "SSTREET_ADD=${{ secrets.SSTREET_ADD }}" >> .env
          echo "SZIP_CODE=${{ secrets.SZIP_CODE }}" >> .env
          echo "SCOUNTRY=${{ secrets.SCOUNTRY }}" >> .env

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Execute Playwright Tests and upload results to Currents
        continue-on-error: false
        working-directory: ./tests
        env:
          CURRENTS_PROJECT_ID: ${{ secrets.CURRENTS_PROJECT_ID }}
          CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}
        run: |
          echo "Running shard ${{ matrix.shard }} of ${{ matrix.shardTotal }}"
          npx pwc --shard=${{ matrix.shard }}/${{matrix.shardTotal}}
